model_name: "nomic-ai/gpt4all-j"
tokenizer_name: "nomic-ai/gpt4all-j"
gradient_checkpointing: True
save_name:  None

# dataset
streaming: False
num_proc: 64
dataset_path: None
max_length: 1024
batch_size: 2

# train dynamics
lr: 2.0e-5
min_lr: 0 
weight_decay: 0.0
eval_every: 500
eval_steps: 105
save_every: 500
log_grads_every: 100
output_dir: None
checkpoint: None
lora: False
warmup_steps: 500
num_epochs: 2 

  # logging
  "wandb": None
  "wandb_entity": None
  "wandb_project_name": None
  "seed": 42